### ISSUE TITLE
Analysis: Level of ambition for PDF design

### ISSUE THREAD

**Issue by lvbachmann** [Altinn/altinn-pdf#13]
## Description
The PDFs we generate at the moment are rather ugly, and we should improve how they look. But we need to decide how far we want to go.

## In scope
- [ ] Conclude on level of customisation
  - [ ] Allow completely custom design?
    - [ ] ... and have a design tool to make it?
  - [ ] Have a standard design with some app owner identifying visual elements?
  - [ ] Have a standard design across the whole of Altinn?
- [ ] Conclude on level of design complexity
  - [ ] Multi column?
  - [ ] Look more like form?
  - [ ] Allow markdown? (#5012)

## Out of scope
TBA

## Analysis
TBA

## Conclusion
TBA

## Tasks
- [ ] Is this issue labeled with a correct area label?
- [ ] QA has been done

**Comment by SandGrainOne** [comment]
All PDF content related features are now outside the scope of the PDF-generator. The PDF-generator will be built to generate PDF from HTML produced by the Apps.
