### ISSUE TITLE
Print/pdf water mark

### ISSUE THREAD

**Issue by JanAage99** [Altinn/altinn-pdf#20]
**Description**
As an end user I want AR-number (or similar (GUID)), date and an optionally name/id of end user included on pp of service-instance so that I have documented that serivce-instance have been sent in.

This issue is related to Altinn/altinn-studio#928 and Altinn/altinn-studio#1048

**Sketch (if relevant)**
(Screenshot or link to Figma, make sure your sketch is public!)

**Technical considerations**
Input (beyond tasks) on how the user story should be solved can be put here.

**Acceptance criterea**
- What is allowed/not allowed (negative tesing)
- Validations
- Error messages and warnings
- ...

**Tasks**
- [ ] Verify that this issue is labeled and written correctly (remove unused stuff, add missing stuff, verify tasks). DoP.
- [ ] Documentation (if relevant)
- [ ] Test / QA (if relevant)

**Comment by ivarne** [comment]
Isn't this covered by the `Referansenummer` at the top of the PDF? 
![image](https://user-images.githubusercontent.com/131616/172870524-a7aa2466-974e-4ab3-a348-f1527e43553b.png)
It's not the full GUID, but should be long enough to be unique.

**Comment by SandGrainOne** [comment]
This is out of scope for the new PDF-generator. The assumption is that the Apps using the PDF generator is able to add a print spesific element to the page being converted to PDF.
