### ISSUE TITLE
PDF generation overflows for very long texts

### ISSUE THREAD

**Issue by lorang92** [Altinn/altinn-pdf#24]
## Description
When supplying very long texts to the pdf generator, the text is cut off. The text is still include and can be read by a machine, but the print out for a user will not include the text.

This is only for long texts, where we are getting cutoffs on texts with 6205 chars, which is considered an edge case. 

## Screenshots
![image](https://user-images.githubusercontent.com/10416981/68028173-75ab8a80-fcb4-11e9-9271-75a92a32589e.png)

## Tasks
- [ ] Investigate possible solution
- [ ] Implement
- [ ] Manual test (if needed)
- [ ] Automatic test (if needed)

**Comment by altinnadmin** [comment]
@lorang92 You mean it's "cut" in the sense that very long texts does not flow over to the next page in the PDF?

**Comment by lorang92** [comment]
@altinnadmin yes, it's cut. There is not implemented any logic to handle a text box spanning multiple pages as of now. It's not directly clear to me how to best implement this, as the text box is connected to a specific page. A possible solution is to split the long texts into multiple text boxes, but that would probably not be preferable for solutions that are going to programmatically read the pdf, as they would have to loop over several text boxes in order to get the full value. 

So, some investigation needs to be done before I know the best way forward.

**Comment by lvbachmann** [comment]
Edge case - could possibly be later than CD Phase 1 too.

**Comment by SandGrainOne** [comment]
This issue is stale and an edge case we're not prioritising at this time.

Also, all PDF content related features are now outside the scope of the PDF-generator. The PDF-generator will be built to generate PDF from HTML produced by the Apps.
