### ISSUE TITLE
Create additional apps for testing of PDF

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-pdf#33]
### Description

Update the selected apps with correct version of the template and have them deployed to the selected environment. 

The goal with the apps should be to test the resulting PDF for UA support.

### Additional Information

Test apps can currently be deployed to AT21 for TTD.

We decieded (16.08.2022) to initially use the following existing apps for testing: 
- UI-components
- Relle rettighetshavere (BR)
- Foreldrebetaling (DiHE)

NuGet packages with client code has been published with release [6.1.0-preview.0](https://www.nuget.org/packages/Altinn.App.PlatformServices/6.1.0-preview.0)

There are 2 new required settings and 2 optional settings to choose from:

1. PdfGeneratorSettings.ServiceEndpointUri (required)
    This should hold the Uri to the new PDF generator service endpoint.
    E.g: https://ttd.apps.at21.altinn.cloud/pdf
2. PdfGeneratorSettings.AppPdfPageUriTemplate (required)
    Template for the URI The PDF generator should request for when generating PDF.
    Value: https://{hostname}/{appId}/#/instance/{instanceid}
    This was made a template to support dev. The value should be the same in all other environments.
3. PdfGeneratorSettings.WaitForTime (optional, default is 5000 ms)
    A hard coded delay to allow the app to render a page before generating the PDF. This is ignored if WaitForSelector is defined.
4. PdfGeneratorSettings.WaitForSelector (optional)
    Give puppeteer a specific html selector. Wait for the identified html element before generating the PDF. This overrides WaitForTime.

In App.cs add a call to the PdfService to generate the pdf.

### Tasks

- [x] UI-components: ttd/pdf-test-ui-components
  - Hard coded the pdf-generator while waiting for instructions
- [x] Relle rettighetshavere (BR): ttd/pdf-test-rrh-innrapportering
  - Removed all logic that requires maskinporten authentication, but compoents are as is. 
  - Removed logic for clearing form data. 
~~- [ ] Foreldrebetaling (DiHE): ttd/pdf-test-foreldrebetaling~~
  - Disabled eFormidling integration
  - Removed all DAN integration
  - Challenges with app logic requiring specific testdata and DAN-access
- Kjærestebesøk: ttd.apps.at21.altinn.cloud/ttd/pdf-test-kjaerestebesok/
### Acceptance Criterias

The selected apps are deployed to correct environment with updated code:

- [x] UI-components
- [x] Relle rettighetshavere (BR)
~~- [ ] Foreldrebetaling (DiHE)~~
- [x] Kjærestebesøk

### PDFs
[UI components app](https://github.com/Altinn/altinn-pdf/files/9488902/experimental.1.pdf)
https://ttd.apps.at21.altinn.cloud/ttd/pdf-test-ui-components

[Reelle rettighetshavere](https://github.com/Altinn/altinn-pdf/files/9489016/experimental.3.pdf)
https://ttd.apps.at21.altinn.cloud/ttd/pdf-test-rrh-innrapportering

[Kjærestebesøk](https://github.com/Altinn/altinn-pdf/files/9490771/experimental.4.pdf)
https://ttd.apps.at21.altinn.cloud/ttd/pdf-test-kjaerestebesok

**Comment by acn-sbuad** [comment]
Issue is missing some information. What else needs to be done except reference the new version of the nuget package?
