### ISSUE TITLE
Automated deploy of the PDF generator app in apps cluster

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-pdf#43]
### Description

The process of deploying a new version of the PDF-generator to all apps clusters must be automated.

### Additional Information

It's important to note that we don't want it to be possible to send requests directly to the PDF generator from outside k8-cluster. The application should be available only for the apps that have been deployed in the cluster.

The PDF-generator should be in a namespace separate from the Apps. Idea: `pdf`

Release pipeline should have stages for atx and yt01, but not for TT02 or production. 

Helm charts for "PDF-Service" (private repo): [dev.azure.com/brreg/altinn-apps-ops](https://dev.azure.com/brreg/altinn-apps-ops/_git/altinn-apps-ops?version=GBfeature/HelmChartsForPdfGenerator&path=/pdf-deployment)

Commands:
```
helm repo add truecharts https://charts.truecharts.org/
helm install pdf-generator truecharts/browserless-chrome --version 3.0.2
```

### Tasks

- [x] Create a Release pipeline that can be run manually when we want to deploy a new version of the PDF-generator
~~- [ ] The deployment should initially use the truecharts charts for browseless/chrome. See commands above. Remember to target correct k8 service.~~

### Test
- [x] Deploy to all AT envs. Ensure pods start successfully in cluster 

### Acceptance Criterias

- [x] Requests directly towards the PDF-generator results in 418 - I'm a Teapot (It's an unknown endpoint)
- [x] An App with correct endpoint address can still produce a PDF.
- [x] Deployment is in the pdf namespace
