### ISSUE TITLE
Run tests for performance testing of the PDF-generator

### ISSUE THREAD

**Issue by borgethommesen** [Altinn/altinn-pdf#44]
### Description

Run tests for performance testing of the PDF-generator (ref #34 )

The goal is to find good values for resource allocation/reservation for the PDF-generator.

The primary concern is to identify a memory limit. Generating PDF will require a lot of memory and we want to prevent the PDF generator from taking all the memory on the nodes.

Identify differences in time between cold and warm "state".

### Tasks

- [x] Prepare scripts and necessary resources to perform a test
- [x] Change the deployment to allow access to the "dashboard" on the pdf-generator.
- [x] Perform a test in a test-meeting with the team as a group exercise
- [x] Experiment with settings like number of replicas, memory and cpu allocation/limits.

**Comment by acn-sbuad** [comment]
Deployed app to at21. 

ttd.apps.at21.altinn.cloud/ttd/new-pdf-load-test/
Available endpoints: 
- [Static apps test html](https://ttd.apps.at21.altinn.cloud/ttd/new-pdf-load-test/api/HTML/apps-test)
- [Static minimal HTML](https://ttd.apps.at21.altinn.cloud/ttd/new-pdf-load-test/api/HTML/simple)


Trigger generation of pdf: 
- [Trigger pdf gen of minimal html](https://ttd.apps.at21.altinn.cloud/ttd/new-pdf-load-test/api/generate?html=simple)
- [Trigger pdf gen of apps-test html](https://ttd.apps.at21.altinn.cloud/ttd/new-pdf-load-test/api/generate?html=apps-test)

Trigger generation of pdf & return HTML
- [Trigger pdf gen of minimal html and return html](https://ttd.apps.at21.altinn.cloud/ttd/new-pdf-load-test/api/generate?html=simple&returnHtml=true)
- [Trigger pdf gen of apps-test html and return html](https://ttd.apps.at21.altinn.cloud/ttd/new-pdf-load-test/api/generate?html=apps-test&returnHtml=true)
