### ISSUE TITLE
Create a test App for load testing the PDF-generator

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-pdf#48]
### Description

The goal here is to have a realistic call chain that includes an App, but with as little overhead in the App as possible. The App should provide some static HTML that the PDF-generator can request when generating a PDF.

- The App must have a new endpoint that can provide the HTML page to turn into a PDF. This should be as static as possible to ensure the page is delivered and rendered quickly. Consider making an expandable endpoint path so that tests can get HTML of different sizes/complexity.
- The App must create a request for the PDF-generator to create a PDF. The idea is to use a stateless app to avoid making a lot of instances. 
- App should allow annonymous access. 
- No need to keep the PDF.
- The HTML being delivered can be based on HTML being produced by an actual app. E.g The summary page of Reelle rettighetshavere. 
- The app should be able to deliever different pages based on an input parameter

### Tasks

- [x] Give the App a new endpoint that provides the test HTML. New controller that returns a view/cshtml. Start simple.
- [x] Create a new PDF-testing app with a stateless view that can trigger PDF-generator when it's started.

### Acceptance Criterias

- [x] New app, stateless and allows annonymous access.
- [x] New app that requests a PDF on a separate page in the App when it starts.
- [x] A HTML Page is availbale directly and annonymously on static endpoint.

**Comment by acn-sbuad** [comment]
Deployed app to at21. 

ttd.apps.at21.altinn.cloud/ttd/new-pdf-load-test/
Available endpoints: 
- [Static apps test html](https://ttd.apps.at21.altinn.cloud/ttd/new-pdf-load-test/api/HTML/apps-test)
- [Static minimal HTML](https://ttd.apps.at21.altinn.cloud/ttd/new-pdf-load-test/api/HTML/simple)


Trigger generation of pdf: 
- [Trigger pdf gen of minimal html](https://ttd.apps.at21.altinn.cloud/ttd/new-pdf-load-test/api/generate?html=simple)
- [Trigger pdf gen of apps-test html](https://ttd.apps.at21.altinn.cloud/ttd/new-pdf-load-test/api/generate?html=apps-test)

Trigger generation of pdf & return HTML
- [Trigger pdf gen of minimal html and return html](https://ttd.apps.at21.altinn.cloud/ttd/new-pdf-load-test/api/generate?html=simple&returnHtml=true)
- [Trigger pdf gen of apps-test html and return html](https://ttd.apps.at21.altinn.cloud/ttd/new-pdf-load-test/api/generate?html=apps-test&returnHtml=true)
