### ISSUE TITLE
PDF-generator Performance test - additional work

### ISSUE THREAD

**Issue by borgethommesen** [Altinn/altinn-pdf#55]
### Description

Report consumption of memory and CPU.
Report number of concurrent connections.
Report queue length
Report working threads.
Report throughput (Number of successful generated pdfs per second / minute).

Generate work load as a combination of sizes Small, Medium and Large PDF.
How should the work load combination be set up and spread between each size?
Number of iterations?
Duration?

What is the performance impact of vertical and horizontal scaling ?
Perform test without scaling.
Perform tests with vertical scaling (more powerful resources)
Perform tests with horizontal scaling (higher number of resources).
Peform tests with both horizontal and verical scaling.

Previous scripts : https://github.com/Altinn/altinn-pdf/issues/34 
Previous test runs : https://github.com/Altinn/altinn-pdf/issues/44
Previous analysis : https://github.com/Altinn/altinn-pdf/issues/45

### Additional Information
No response

### Tasks
- [x] Develop new scripts or adapt existing scripts.
- [x] Perform tests
  - [x] Perform test without scaling.
  - [x] Perform tests with vertical scaling (more powerful resources)
  - [x] Perform tests with horizontal scaling (higher number of resources).
  - [x] Perform tests with both horizontal and verical scaling.
- [x] Check necessary perfomance data in relevant tools. K6-results, Azure Monitoring, Azure Insight.
- [x] Analyze performance data
- [ ] Report performance data

### Acceptance Criterias
- [x] Test scripts developed
- [x] Test runs performed
- [x] Performance data analyzed
- [ ] Performance report completed

**Comment by bdb-dd** [comment]
Adding a comment here to document my additional findings.

Testing with constantvu configuration indicates that the overall throughput of the pdf service stays very constant given a consistent and stable supply of new requests. This indicates that there is no capacity scaling activated currently. Is there any possibility that our test app could be the bottleneck here?

It would be good to document and verify how we expect the service to increase it's capacity dynamically at runtime, either by increasing the number of worker processes in a single pod and/or multiple pods in a given node pool.

It should also be noted that overall throughput (PDFs generated per second) goes down as soon as the number of load test threads (VUs) exceeds the number of pdf generation workers.
