### ISSUE TITLE
Deploy pdf generator to Prod apps cluster 

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-pdf#58]
### Description

Currently, [the release pipeline](https://dev.azure.com/brreg/altinn-studio/_release?_a=releases&view=all&definitionId=43) supports deployment to clusters in AT, YT01 and TT02. 
This should be extended to production. 

Environment variable: PdfGeneratorSettings__ServiceEndpointUri=http://pdf-generator.pdf.svc.cluster.local/pdf

### Tasks
  - [x] Add missing stages with correct deployment gates and schedules
  - [x] Add environment variable in app deployment pipeline
  - [x] Regression test deploy pipeline
  - [x] Run deployment pipeline for prod

### Acceptance Criterias

- [x] PDF generator exists in all apps cluster in production

**Comment by acn-sbuad** [comment]
Bug in app frontend. Waiting 'til this is fixed before we deploy
