### ISSUE TITLE
Enable startup, readiness and liveness probes 

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-pdf#59]
### Description

Currently we have no probes set up. These should be set up and enabled

### Tasks

- [x] Investigate endpoints exposed for support for probes 
- [x] Update helm charts
- [x] QA
- [x] Test

### Acceptance Criterias

- [x] Readiness probe is enabled
- [x] Liveness probe is enabled
- [x] Startup probe is enabled

**Comment by acn-sbuad** [comment]
https://github.com/Altinn/altinn-studio-charts/pull/21
